In [1]:
import nltk
import pickle
import pandas as pd
import re
import string
from nltk.stem import WordNetLemmatizer 
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\roych\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [2]:
# Reading the dataset
df = pd.read_csv('combined_data.csv')

In [3]:
df.head()

label                                               text
0      1  ounce feather bowl hummingbird opec moment ala...
1      1  wulvob get your medircations online qnb ikud v...
2      0   computer connection from cnn com wednesday es...
3      1  university degree obtain a prosperous future m...
4      0  thanks for all your answers guys i know i shou...

In [4]:
len(df)

83448

In [5]:
#df = dataset[0:10000]

In [6]:
stopwords = nltk.corpus.stopwords.words('english')
lemmatizer = WordNetLemmatizer() 

In [7]:
# Preprocessing
nltk.download('stopwords')
corpus = []
for i in range(0, 83448):
    result = re.sub('[^a-zA-Z]', ' ', df['text'][i])
    result = result.lower()
    result = result.split()
    result = [lemmatizer.lemmatize(word) for word in result if not word in set(stopwords)]
    result = ' '.join(result)
    corpus.append(result)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\roych\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [8]:
df[10:11].values

array([[1,
        'my dear fellow do you feel insecure about your penis size you need our new improved megadik penis enlargement pills please read on did you know megadik was featured in leading mens magazines such as fhm maxim plus many others and rated no escapenumber choice for penis enlargement » gain escapenumber inches in length » increase your penis width girth by upto escapenumber » produce stronger rock hard erections » escapenumber safe to take with no side effects » doctor approved and recommended » fast shipping worldwide you have nothing to lose just a lot to gain http slasy net regards escapelong remains in escapelong use escapenumberf milliescapenumberns escapenumberf peescapenumberple in this wescapenumberrld i am escapelong man and alescapenumberng with all thescapenumberse milliescapenumberns although far from perfect especially in that it precludes a vast waldron']],
      dtype=object)

In [9]:
df.iloc[10].values

array([1,
       'my dear fellow do you feel insecure about your penis size you need our new improved megadik penis enlargement pills please read on did you know megadik was featured in leading mens magazines such as fhm maxim plus many others and rated no escapenumber choice for penis enlargement » gain escapenumber inches in length » increase your penis width girth by upto escapenumber » produce stronger rock hard erections » escapenumber safe to take with no side effects » doctor approved and recommended » fast shipping worldwide you have nothing to lose just a lot to gain http slasy net regards escapelong remains in escapelong use escapenumberf milliescapenumberns escapenumberf peescapenumberple in this wescapenumberrld i am escapelong man and alescapenumberng with all thescapenumberse milliescapenumberns although far from perfect especially in that it precludes a vast waldron'],
      dtype=object)

In [10]:
corpus[10:11]

['dear fellow feel insecure penis size need new improved megadik penis enlargement pill please read know megadik featured leading men magazine fhm maxim plus many others rated escapenumber choice penis enlargement gain escapenumber inch length increase penis width girth upto escapenumber produce stronger rock hard erection escapenumber safe take side effect doctor approved recommended fast shipping worldwide nothing lose lot gain http slasy net regard escapelong remains escapelong use escapenumberf milliescapenumberns escapenumberf peescapenumberple wescapenumberrld escapelong man alescapenumberng thescapenumberse milliescapenumberns although far perfect especially precludes vast waldron']

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

In [12]:
# Creating the Bag of Words model
cv = CountVectorizer(max_features = 2500)

# Fitting the vectorizer to the corpus
cv.fit(corpus)

# Transforming the corpus into the bag of words model
X = cv.transform(corpus).toarray()

# Extracting the dependent variable
y = df.iloc[:, 0].values


In [13]:
y

array([1, 1, 0, ..., 1, 0, 1], dtype=int64)

In [14]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [15]:
X.shape

(83448, 2500)

In [16]:
print(len(X[10]))

2500


In [17]:
from sklearn.model_selection import train_test_split
# Splitting the dataset into the Training set and Test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 7)

In [18]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(62586, 2500)
(62586,)
(20862, 2500)
(20862,)


In [19]:
#using Random Forest Classifier

from sklearn.ensemble import RandomForestClassifier
# Random Forest
classifier = RandomForestClassifier(n_estimators = 20, criterion = 'entropy', random_state = 7)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

In [20]:
#accuracy score and classification report

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [21]:
accuracy_score(y_test, y_pred)

0.9779503403317036

In [22]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98      9881
           1       0.98      0.98      0.98     10981

    accuracy                           0.98     20862
   macro avg       0.98      0.98      0.98     20862
weighted avg       0.98      0.98      0.98     20862



In [23]:
#doing a test prediction

test = ["promo mail get flat 50% off on this, get many offers in store and see all stock by yourself"]

In [24]:
review = re.sub('[^a-zA-Z]', ' ', test[0])
review = review.lower()
review = review.split()
review = [lemmatizer.lemmatize(word) for word in review if not word in set(stopwords)]
review = ' '.join(review)
t1=[review]

In [25]:
t1

['promo mail get flat get many offer store see stock']

In [26]:
#transforming for using on the model (using the count vectorizer)

test_vec = cv.transform(t1)

In [27]:
test_vec[0]

<1x2500 sparse matrix of type '<class 'numpy.int64'>'
	with 7 stored elements in Compressed Sparse Row format>

In [28]:
#spam 1
#ham 0
classifier.predict(test_vec)[0]

1

In [29]:
print(test_vec)

  (0, 936)	2
  (0, 1306)	1
  (0, 1326)	1
  (0, 1503)	1
  (0, 1964)	1
  (0, 2137)	1
  (0, 2141)	1


In [30]:
#doing a test prediction

test = ["Dear Ms. Smith, I am writing to request personal leave from July 15th to July 20th. During this period, I will be attending a family event out of town. I understand the impact of my absence and will ensure that my responsibilities are covered during this time. If there are any specific procedures or forms required for leave approval, please let me know. Thank you for your understanding, and I appreciate your prompt attention to this matter."]

In [31]:
review = re.sub('[^a-zA-Z]', ' ', test[0])
review = review.lower()
review = review.split()
review = [lemmatizer.lemmatize(word) for word in review if not word in set(stopwords)]
review = ' '.join(review)
t1=[review]

In [32]:
t1

['dear m smith writing request personal leave july th july th period attending family event town understand impact absence ensure responsibility covered time specific procedure form required leave approval please let know thank understanding appreciate prompt attention matter']

In [33]:
#transforming for using on the model (using the count vectorizer)

test_vec = cv.transform(t1)

In [34]:
print(test_vec)

  (0, 111)	1
  (0, 115)	1
  (0, 151)	1
  (0, 481)	1
  (0, 529)	1
  (0, 708)	1
  (0, 761)	1
  (0, 820)	1
  (0, 890)	1
  (0, 1071)	1
  (0, 1167)	2
  (0, 1190)	1
  (0, 1224)	2
  (0, 1233)	1
  (0, 1342)	1
  (0, 1606)	1
  (0, 1610)	1
  (0, 1646)	1
  (0, 1723)	1
  (0, 1745)	1
  (0, 1864)	1
  (0, 1867)	1
  (0, 1878)	1
  (0, 2054)	1
  (0, 2086)	1
  (0, 2236)	2
  (0, 2238)	1
  (0, 2258)	1
  (0, 2284)	1
  (0, 2331)	1
  (0, 2332)	1
  (0, 2480)	1


In [35]:
#spam 1
#ham 0
classifier.predict(test_vec)[0]

0

In [36]:
# Saving the CountVectorizer
with open('count_vectorizer.pkl', 'wb') as f:
    pickle.dump(cv, f)

# Saving the classifier
with open('classifier.pkl', 'wb') as f:
    pickle.dump(classifier, f)